name: Variable test

on:
  push:
    branches:
      - main

env:
  MY_WORKFLOW_VARIABLE: "This is a workflow-level variable"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VARIABLE: "This is a job-level variable"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Workflow-Level Variable
        run: echo $MY_WORKFLOW_VARIABLE

      - name: Print Job-Level Variable
        run: echo $MY_JOB_VARIABLE

      - name: My Step
        env:
          MY_STEP_VARIABLE: "This is a step-level variable"
        run: |
          echo $MY_STEP_VARIABLE
